In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
print("WorldCup Intelligence Platform")
print("Data Discovery")

WorldCup Intelligence Platform
Data Discovery

In [4]:
pip install statsbombpy

Requirement already satisfied: statsbombpy in E:\Python\worldcup-intelligence-platform\.venv\Lib\site-packages (1.19.0)
Requirement already satisfied: pandas in E:\Python\worldcup-intelligence-platform\.venv\Lib\site-packages (from statsbombpy) (3.0.3)
Requirement already satisfied: requests in E:\Python\worldcup-intelligence-platform\.venv\Lib\site-packages (from statsbombpy) (2.34.2)
Requirement already satisfied: requests-cache in E:\Python\worldcup-intelligence-platform\.venv\Lib\site-packages (from statsbombpy) (1.3.2)
Requirement already satisfied: inflect in E:\Python\worldcup-intelligence-platform\.venv\Lib\site-packages (from statsbombpy) (7.5.0)
Requirement already satisfied: joblib in E:\Python\worldcup-intelligence-platform\.venv\Lib\site-packages (from statsbombpy) (1.5.3)
Requirement already satisfied: more_itertools>=8.5.0 in E:\Python\worldcup-intelligence-platform\.venv\Lib\site-packages (from inflect->statsbombpy) (11.1.0)
Requirement already satisfied: typeguard>=4.0.1 in E:\Python\worldcup-intelligence-platform\.venv\Lib\site-packages (from inflect->statsbombpy) (4.5.2)
Requirement already satisfied: typing_extensions>=4.14.0 in E:\Python\worldcup-intelligence-platform\.venv\Lib\site-packages (from typeguard>=4.0.1->inflect->statsbombpy) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in E:\Python\worldcup-intelligence-platform\.venv\Lib\site-packages (from pandas->statsbombpy) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in E:\Python\worldcup-intelligence-platform\.venv\Lib\site-packages (from pandas->statsbombpy) (2.9.0.post0)
Requirement already satisfied: tzdata in E:\Python\worldcup-intelligence-platform\.venv\Lib\site-packages (from pandas->statsbombpy) (2026.2)
Requirement already satisfied: six>=1.5 in E:\Python\worldcup-intelligence-platform\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas->statsbombpy) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in E:\Python\worldcup-intelligence-platform\.venv\Lib\site-packages (from requests->statsbombpy) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in E:\Python\worldcup-intelligence-platform\.venv\Lib\site-packages (from requests->statsbombpy) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in E:\Python\worldcup-intelligence-platform\.venv\Lib\site-packages (from requests->statsbombpy) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in E:\Python\worldcup-intelligence-platform\.venv\Lib\site-packages (from requests->statsbombpy) (2026.6.17)
Requirement already satisfied: attrs>=21.2 in E:\Python\worldcup-intelligence-platform\.venv\Lib\site-packages (from requests-cache->statsbombpy) (26.1.0)
Requirement already satisfied: cattrs>=22.2 in E:\Python\worldcup-intelligence-platform\.venv\Lib\site-packages (from requests-cache->statsbombpy) (26.1.0)
Requirement already satisfied: platformdirs>=2.5 in E:\Python\worldcup-intelligence-platform\.venv\Lib\site-packages (from requests-cache->statsbombpy) (4.10.0)
Requirement already satisfied: url-normalize>=2.0 in E:\Python\worldcup-intelligence-platform\.venv\Lib\site-packages (from requests-cache->statsbombpy) (3.0.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
pip show statsbombpy

Name: statsbombpy
Version: 1.19.0
Summary: easily stream StatsBomb data into Python
Home-page: https://github.com/statsbomb/statsbombpy
Author: StatsBomb
Author-email: support@statsbombservices.com
License: UNKNOWN
Location: E:\Python\worldcup-intelligence-platform\.venv\Lib\site-packages
Requires: inflect, joblib, pandas, requests, requests-cache
Required-by:
Note: you may need to restart the kernel to use updated packages.

In [6]:
from statsbombpy import sb

In [7]:
competitions = sb.competitions()
competitions.head()

E:\Python\worldcup-intelligence-platform\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-11-15T23:17:41.827093,2025-11-15T23:17:41.827093,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,NaN,NaN,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396,2026-05-02T02:07:18.902396,2026-05-12T21:18:08.827431
3,16,4,Europe,Champions League,male,False,False,2018/2019,2026-05-15T15:54:04.598614,2021-06-13T16:17:31.694,NaN,2026-05-15T15:54:04.598614
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,NaN,2024-02-13T02:35:28.134882

In [8]:
competitions.columns

Index(['competition_id', 'season_id', 'country_name', 'competition_name',
       'competition_gender', 'competition_youth', 'competition_international',
       'season_name', 'match_updated', 'match_updated_360',
       'match_available_360', 'match_available'],
      dtype='str')

In [9]:
competitions.shape

(80, 12)

In [10]:
world_cups = competitions[
    competitions["competition_name"].str.contains(
        "World Cup",
        case = False,
        na = False
    )
    ]

In [11]:
world_cups[
    [
        "competition_id",
        "season_id",
        "competition_name",
        "season_name"
    ]
    ]

    competition_id  season_id    competition_name season_name
29            1470        274  FIFA U20 World Cup        1979
30              43        106      FIFA World Cup        2022
31              43          3      FIFA World Cup        2018
32              43         55      FIFA World Cup        1990
33              43         54      FIFA World Cup        1986
34              43         51      FIFA World Cup        1974
35              43        272      FIFA World Cup        1970
36              43        270      FIFA World Cup        1962
37              43        269      FIFA World Cup        1958
78              72        107   Women's World Cup        2023
79              72         30   Women's World Cup        2019

In [14]:
matches_2022 = sb.matches(
    competition_id = 43,
    season_id = 106)

matches_2022.head()

E:\Python\worldcup-intelligence-platform\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,...,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,data_version,shot_fidelity_version,xy_fidelity_version
0,3857276,2022-12-01,15:00:00.000,1,2,available,available,2026-05-04T01:46:04.664252,2026-05-04T01:50:33.318123,3,...,England,1000518,Walid Regragui,NaN,1975-09-23,154,Morocco,1.1.0,2,2
1,3857271,2022-11-21,13:00:00.000,6,2,available,available,2026-05-04T01:40:47.671394,2026-05-04T01:43:30.216315,1,...,England,645,Carlos Manuel Brito Leal Queiróz,Carlos Queiroz,1953-03-01,183,Portugal,1.1.0,2,2
2,3857296,2022-12-01,15:00:00.000,0,0,available,available,2026-05-04T01:44:02.255386,2026-05-04T01:50:06.343225,3,...,Croatia,263,Roberto Martínez Montoliú,Roberto Martínez,1973-07-13,214,Spain,1.1.0,2,2
3,3857274,2022-11-25,16:00:00.000,1,1,available,available,2026-05-04T01:43:00.444702,2026-05-04T01:50:07.646458,2,...,Netherlands,2881,Gustavo Julio Alfaro,Gustavo Alfaro,1962-08-14,11,Argentina,1.1.0,2,2
4,3857255,2022-12-01,19:00:00.000,2,1,available,available,2026-05-04T01:42:55.630428,2026-05-04T01:49:36.594944,3,...,Japan,793,Luis Enrique Martínez García,Luis Enrique,1970-05-08,214,Spain,1.1.0,2,2

In [16]:
matches_2022.shape

(64, 55)

In [17]:
matches_2022.columns

Index(['match_id', 'match_date', 'kick_off', 'home_score', 'away_score',
       'match_status', 'match_status_360', 'last_updated', 'last_updated_360',
       'match_week', 'competition_id', 'competition_country_name',
       'competition_name', 'competition', 'season_id', 'season',
       'home_team_id', 'home_team', 'home_team_gender', 'home_team_group',
       'home_team_country_id', 'home_team_country_name', 'away_team_id',
       'away_team', 'away_team_gender', 'away_team_group',
       'away_team_country_id', 'away_team_country_name',
       'competition_stage_id', 'competition_stage', 'stadium_id', 'stadium',
       'stadium_country_id', 'stadium_country_name', 'referee_id', 'referee',
       'referee_country_id', 'referee_country_name', 'home_managers',
       'away_managers', 'home_manager_id', 'home_manager_name',
       'home_manager_nickname', 'home_manager_dob', 'home_manager_country_id',
       'home_manager_country_name', 'away_manager_id', 'away_manager_name',
       'away_manager_nickname', 'away_manager_dob', 'away_manager_country_id',
       'away_manager_country_name', 'data_version', 'shot_fidelity_version',
       'xy_fidelity_version'],
      dtype='str')

In [19]:
matches_2022[
    [
        "home_team",
        "away_team",
        "home_score",
        "away_score"
    ]
    ].head(10)

     home_team      away_team  home_score  away_score
0       Canada        Morocco           1           2
1      England           Iran           6           2
2      Croatia        Belgium           0           0
3  Netherlands        Ecuador           1           1
4        Japan          Spain           2           1
5      England  United States           0           0
6         Iran  United States           0           1
7      Morocco        Croatia           0           0
8        Wales           Iran           0           2
9      Tunisia         France           1           0

In [25]:
home_score = 0
away_score = 0

if home_score > away_score:
    winner = "Home Team"
elif away_score > home_score:
    winner = "Away Team"
else: winner = "Draw"

print(winner)

Draw

In [26]:
matches_2022[
    [
        "match_id",
        "home_team",
        "away_team",
        "home_score",
        "away_score",
        "competition_stage"
    ]
].tail(10)

,match_id,home_team,away_team,home_score,away_score,competition_stage
54,3857283,Belgium,Morocco,0,2,Group Stage
55,3857286,Qatar,Ecuador,0,2,Group Stage
56,3857300,Argentina,Saudi Arabia,1,2,Group Stage
57,3857299,South Korea,Ghana,2,3,Group Stage
58,3857293,Ghana,Uruguay,0,2,Group Stage
59,3857291,Spain,Costa Rica,7,0,Group Stage
60,3857281,Croatia,Canada,4,1,Group Stage
61,3857280,Cameroon,Brazil,1,0,Group Stage
62,3857279,France,Australia,4,1,Group Stage
63,3857262,South Korea,Portugal,2,1,Group Stage

In [27]:
matches_2022["competition_stage"].value_counts()

competition_stage
Group Stage        48
Round of 16         8
Quarter-finals      4
Semi-finals         2
Final               1
3rd Place Final     1
Name: count, dtype: int64

In [28]:
matches_2022["competition_stage"].unique()

<StringArray>
[    'Group Stage',  'Quarter-finals',           'Final', '3rd Place Final',
     'Round of 16',     'Semi-finals']
Length: 6, dtype: str

In [29]:
matches_2022["home_team"].nunique()

32

In [30]:
matches_2022["away_team"].nunique()

32

In [37]:
def determine_winner(row):

    if row["home_score"] > row["away_score"]:
        return row["home_team"]

    elif row["away_score"] > row["home_score"]:
        return row["away_team"]

    else:
        return "Draw"

In [39]:
matches_2022["winner"] = matches_2022.apply(
    determine_winner,
    axis = 1
)

In [40]:
matches_2022[
    [
        "home_team",
        "away_team",
        "home_score",
        "away_score",
        "winner"
    ]
].head(10)

     home_team      away_team  home_score  away_score         winner
0       Canada        Morocco           1           2        Morocco
1      England           Iran           6           2        England
2      Croatia        Belgium           0           0           Draw
3  Netherlands        Ecuador           1           1           Draw
4        Japan          Spain           2           1          Japan
5      England  United States           0           0           Draw
6         Iran  United States           0           1  United States
7      Morocco        Croatia           0           0           Draw
8        Wales           Iran           0           2           Iran
9      Tunisia         France           1           0        Tunisia

In [41]:
matches_2022["winner"].value_counts()

winner
Draw             15
France            5
Argentina         4
Morocco           3
England           3
Portugal          3
Netherlands       3
Brazil            3
Japan             2
Switzerland       2
Senegal           2
Croatia           2
Australia         2
United States     1
Iran              1
Tunisia           1
Poland            1
Belgium           1
Germany           1
Costa Rica        1
Mexico            1
Ecuador           1
Saudi Arabia      1
Ghana             1
Uruguay           1
Spain             1
Cameroon          1
South Korea       1
Name: count, dtype: int64

In [50]:
def determine_result_type(row):
    if row["home_score"] > row["away_score"]:
        return "Home Win"

    elif row["away_score"] > row["home_score"]:
        return "Away Win"

    else:
        return "Draw"

In [51]:
matches_2022["result_type"] = matches_2022.apply(
    determine_result_type,
    axis = 1
)

In [52]:
matches_2022[
    [
        "home_team",
        "away_team",
        "home_score",
        "away_score",
        "winner",
        "result_type"
    ]
].head(10)

,home_team,away_team,home_score,away_score,winner,result_type
0,Canada,Morocco,1,2,Morocco,Away Win
1,England,Iran,6,2,England,Home Win
2,Croatia,Belgium,0,0,Draw,Draw
3,Netherlands,Ecuador,1,1,Draw,Draw
4,Japan,Spain,2,1,Japan,Home Win
5,England,United States,0,0,Draw,Draw
6,Iran,United States,0,1,United States,Away Win
7,Morocco,Croatia,0,0,Draw,Draw
8,Wales,Iran,0,2,Iran,Away Win
9,Tunisia,France,1,0,Tunisia,Home Win

In [53]:
matches_2022["result_type"].value_counts()

result_type
Home Win    29
Away Win    20
Draw        15
Name: count, dtype: int64