In [1]:
import pandas as pd

In [4]:
matches = pd.read_csv(r"E:\Python\worldcup-intelligence-platform\data\raw\international_results.csv")

In [5]:
matches.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [6]:
matches.shape

(49477, 9)

In [7]:
matches.columns

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='str')

In [8]:
matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 49477 entries, 0 to 49476
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49477 non-null  str
 1   home_team   49477 non-null  str
 2   away_team   49477 non-null  str
 3   home_score  49465 non-null  float64
 4   away_score  49465 non-null  float64
 5   tournament  49477 non-null  str
 6   city        49477 non-null  str
 7   country     49477 non-null  str
 8   neutral     49477 non-null  bool
dtypes: bool(1), float64(2), str(6)
memory usage: 3.1 MB

In [9]:
matches.isnull().sum()

date           0
home_team      0
away_team      0
home_score    12
away_score    12
tournament     0
city           0
country        0
neutral        0
dtype: int64

In [10]:
matches.describe(include="all")

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
count,49477,49477,49477,49465.000000,49465.000000,49477,49477,49477,49477
unique,16471,327,321,NaN,NaN,200,2089,269,2
top,2012-02-29,Brazil,Uruguay,NaN,NaN,Friendly,Kuala Lumpur,United States,False
freq,66,616,585,NaN,NaN,18388,745,1559,36356
mean,NaN,NaN,NaN,1.757404,1.181785,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,1.774147,1.401717,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,1.000000,0.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,1.000000,1.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,2.000000,2.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,31.000000,21.000000,NaN,NaN,NaN,NaN

In [11]:
matches.duplicated().sum()

np.int64(0)

In [12]:
matches[matches["home_score"].isna()]

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49465,2026-06-26,Egypt,Iran,NaN,NaN,FIFA World Cup,Seattle,United States,True
49466,2026-06-26,New Zealand,Belgium,NaN,NaN,FIFA World Cup,Vancouver,Canada,True
49467,2026-06-26,Cape Verde,Saudi Arabia,NaN,NaN,FIFA World Cup,Houston,United States,True
49468,2026-06-26,Uruguay,Spain,NaN,NaN,FIFA World Cup,Zapopan,Mexico,True
49469,2026-06-26,Norway,France,NaN,NaN,FIFA World Cup,Foxborough,United States,True
49470,2026-06-26,Senegal,Iraq,NaN,NaN,FIFA World Cup,Toronto,Canada,True
49471,2026-06-27,Algeria,Austria,NaN,NaN,FIFA World Cup,Kansas City,United States,True
49472,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True
49473,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49474,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49475,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49476,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True

In [13]:
matches["date"].is_monotonic_increasing

False

In [14]:
matches["date"] = pd.to_datetime(matches["date"])

In [15]:
matches["date"].is_monotonic_increasing

False

In [16]:
matches.sort_values("date").head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [17]:
matches.sort_values("date").tail()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49473,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49475,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49471,2026-06-27,Algeria,Austria,NaN,NaN,FIFA World Cup,Kansas City,United States,True
49472,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True
49476,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True

In [18]:
START_YEAR = "2000-01-01"

In [19]:
matches["date"] = pd.to_datetime(matches["date"])

matches = matches.sort_values("date")

matches = matches[matches["date"] >= START_YEAR]

In [20]:
matches.shape

(25415, 9)

In [21]:
matches.dtypes

date          datetime64[us]
home_team                str
away_team                str
home_score           float64
away_score           float64
tournament               str
city                     str
country                  str
neutral                 bool
dtype: object

In [22]:
matches = matches.dropna(subset=["home_score", "away_score"])

In [23]:
matches.shape

(25403, 9)

In [24]:
matches.isnull().sum()

date          0
home_team     0
away_team     0
home_score    0
away_score    0
tournament    0
city          0
country       0
neutral       0
dtype: int64

In [25]:
matches["home_score"] = matches["home_score"].astype(int)
matches["away_score"] = matches["away_score"].astype(int)

In [26]:
matches.dtypes

date          datetime64[us]
home_team                str
away_team                str
home_score             int64
away_score             int64
tournament               str
city                     str
country                  str
neutral                 bool
dtype: object

In [30]:
matches.to_csv(
    r"E:\Python\worldcup-intelligence-platform\data\raw\clean_matches.csv",
    index=False
)